### PR TITLE
Added Chinese translations

### PR DESCRIPTION
**Pull request by Endermanbugzjfc**

### CODE REVIEW

**Comment by cooldogedev** [comment]
you'll have to modify this array in order to fully support the langauge, https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/language/LanguageManager.php#L35.

**Comment by cooldogedev** [comment]
let me know when it's ready so I can merge it

**Comment by Endermanbugzjfc** [comment]
> you'll have to modify this array in order to fully support the langauge, https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/language/LanguageManager.php#L35.

Understandable.

**Comment by cooldogedev** [comment]
everything looks good, thanks for the contribution.

**Pull request merged**
